# Generated by Django 4.2.7 on 2023-12-09 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='admin',
            name='unique_admin_email',
        ),
        migrations.RemoveConstraint(
            model_name='resident',
            name='unique_resident_email',
        ),
        migrations.AlterField(
            model_name='admin',
            name='email',
            field=models.EmailField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='resident',
            name='email',
            field=models.EmailField(blank=True, max_length=30, null=True),
        ),
    ]
