# Generated by Django 4.2.7 on 2024-03-31 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_incidentstatus_status_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentstatus',
            name='status_name',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
